apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gmod-darkrp-kustomization.yaml
- gmod-ttt-kustomization.yaml
- gmod-sandbox-kustomization.yaml
- gmod-starwarsrp-kustomization.yaml
