apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcile: "enabled"
    fluxcd.controlplane.io/reconcileEvery: "1h"
    fluxcd.controlplane.io/reconcileTimeout: "3m"
spec:
  sync:
    kind: GitRepository
    url: "https://github.com/antoniolago/lag0-fleet-infra-ton"
    ref: "refs/heads/main"
    path: "cluster"
    pullSecret: "github-credentials"
  distribution:
    version: "2.x"
    registry: "ghcr.io/fluxcd"
  components:
  - source-controller
  - kustomize-controller
  - helm-controller
  - notification-controller
  - image-reflector-controller
  - image-automation-controller
  cluster:
    type: kubernetes
    multitenant: false
    networkPolicy: true
    domain: "cluster.local"
  storage:
    class: "nfs-csi"
    size: "10Gi"
  commonMetadata:
    labels:
      app.kubernetes.io/name: flux
  kustomize:
    patches:
    - target:
        kind: Deployment
        name: "(kustomize-controller|helm-controller)"
      patch: |
        - op: add
          path: /spec/template/spec/containers/0/args/-
          value: --concurrent=10
        - op: add
          path: /spec/template/spec/containers/0/args/-
          value: --requeue-dependency=5s
        - op: add
          path: /spec/template/spec/containers/0/args/-
          value: --min-retry-delay=5s
