apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tailscale-conf
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./tailscale-ton-conf
  prune: false
  force: false
  sourceRef:
    kind: GitRepository
    name: lag0-fleet-manifests-git
